export const teamMemberType = {
  name: 'teamMember',
  title: 'Team Member',
  type: 'document',
  fields: [
    {
      name: 'memberType',
      title: 'Type',
      type: 'string',
      options: { list: [{ title: 'Principal', value: 'principal' }, { title: 'Associate consultant', value: 'associate' }] },
      initialValue: 'principal',
    },
    { name: 'published', title: 'Show on website', type: 'boolean', initialValue: false },
    { name: 'name', type: 'string' },
    { name: 'role', type: 'string' },
    { name: 'bio', type: 'text' },
    { name: 'yearsConsulting', type: 'number' },
    { name: 'overallExperience', type: 'number' },
    { name: 'qualifications', type: 'array', of: [{ type: 'string' }] },
    { name: 'focusAreas', title: 'Focus areas', type: 'array', of: [{ type: 'string' }] },
    { name: 'sectors', title: 'Key sectors', type: 'array', of: [{ type: 'string' }] },
    { name: 'photo', type: 'image', options: { hotspot: true } },
    { name: 'socialLinks', type: 'object', fields: [{ name: 'twitter', type: 'url' }, { name: 'linkedin', type: 'url' }, { name: 'instagram', type: 'url' }] },
    { name: 'order', type: 'number' },
  ],
}
